# -*- coding: utf-8 -*-
"""PRO-C129-Project-Solution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mMOhmdKx-q40ZbbDoNG1jTBJ2RKMecMo

*Note: The data is scraped from wikipedia webpage and might change in future, hence it might vary!*
"""

!git clone https://github.com/procodingclass/PRO-Stars-Dataset-CSVs

import pandas as pd

df = pd.read_csv("/content/PRO-Stars-Dataset-CSVs/dwarf_stars.csv")
df.head(10)

df.shape

"""## DROP Unnecessary Columns if any, DROP NAN"""

df = df.dropna()
df.info()

df.shape

"""## Remove ALL Special Characters and Convert to correct type

Observe **dwarf stars data** and remove any special characters.

Few of the examples highlighted in the below:

*Note: The data is scraped fro wikipedia webpage and might change in future, hence it might vary!*

*This may lead to differnce in data processing steps too!*

<img src="https://s3-whjr-curriculum-uploads.whjr.online/595398f0-5d0b-475f-ab37-462599e70b4f.png" width=600>
"""

df.Mass = df.Mass.str.replace('[^a-zA-Z0-9]', '').astype('float')

"""## Update Radius and Mass Units"""

df["Radius"] = df["Radius"]*(0.102763)

df["Mass"] = df["Mass"]*(0.000954588)

df.info()

"""## Convert to CSV"""

df.to_csv("unit_converted_stars.csv")
df.dtypes

"""## Download CSV"""

# from google.colab import files
# files.download("unit_converted_stars.csv")

"""# MERGE """

import csv
import pandas as pd

file1 = '/content/PRO-Stars-Dataset-CSVs/bright_stars.csv'
file2 = '/content/PRO-Stars-Dataset-CSVs/unit_converted_stars.csv'

d1 = []
d2 = []
with open(file1,'r',encoding='utf8') as f:
    csv_reader =csv.reader(f)
    
    for i in csv_reader:
        d1.append(i)
        
with open(file2,'r',encoding='utf8') as f:
    csv_reader = csv.reader(f)
    
    for i in csv_reader:
        d2.append(i)

h1 = d1[0]
h2 = d2[0]

p_d1 = d1[1:]
p_d2 = d2[1:]

h = h1+h2

p_d =[]

for i in p_d1:
    p_d.append(i)
for j in p_d2:
    p_d.append(j)

with open("total_stars.csv",'w',encoding='utf8') as f:
    csvwriter = csv.writer(f)
    csvwriter.writerow(h)   
    csvwriter.writerows(p_d)
    
df = pd.read_csv('total_stars.csv')
df.tail(8)

from google.colab import files
files.download("total_stars.csv")